 (001)  2019.11.16  Keyboard shortcuts ( Alt-... )

+(002)  2019.11.16  Keyboard shortcuts ( Enter on selected Item )

 (003)  2019.11.16  Sort columns

+(004)  2019.11.17  OnCharHook stuff to see

+(005)  2019.11.20  Obuscated review

    General stuff:
+   1. no underscores in variable names
+   2. no too much alignment (I don't understand why people want to align unrelated if-then statements, but I guess this is just me)
    3. no abbreviations dvlc and dvls doesn't mean too much if you don't know what are they in the first place
    4. use range-based for loops whenever possible, but no auto variables...
    5. no single line if statements

+(006)  2019.11.20  Obuscated review

    Patch specific:
    1. Public apis must be documented, no matter that the surrounding apis aren't.
+   2. Why do you need a second map? Why don't you make a structure and add a bool? Or just add some kind of a set with inactive or active variables? Prefer hash based containers if you don't need sorting.
    3. xrc files are generated by tools, don't edit them by hand and don't leave commented stuff in them
    4. Why have you changed the names of the buttons? Add and Edit are pretty common in C::B?
    5. You need to provide better commit message.
    6. Why are the new api calls virtual?
+   7. These api calls must be exposed to scripting.

+(007)  2019.11.21  Remove _ERG_CORR_ , _ERG_TODO_ from published files

+(008)  2019.11.21  Add default sorting by name
//  ############################################################################
(001)   2019.11.17  Done properly. Just modify the xrc file.

(002)

(003)   2019.11.16  Done, with wxDATAVIEW_COL_SORTABLE flag

(005)
    1
    2
    3   2019.11.21  Done, m_VarsWxCtrl and m_VarsWxModel
    4   2019.11.21  I dont use auto variables
    5   2019.11.21  Done

(006)
    1   2019.11.21  Done, added some non-trivial comments
    2
    3   2019.11.22  Done in pub scripts
    4   2019.11.20  Changes were accepted by obfuscated
    5   2019.11.21  Will do that from now
    6   2019.11.20  Was accepted by obfuscated
    7
